name: berkeley3
dependencies:
- _license=1.1=py27_1
- abstract-rendering=0.5.1=np110py27_0
- alabaster=0.7.6=py27_0
- anaconda=2.4.1=np110py27_0
- anaconda-client=1.2.1=py27_0
- appnope=0.1.0=py27_0
- appscript=1.0.1=py27_0
- argcomplete=1.0.0=py27_1
- astropy=1.0.6=np110py27_0
- babel=2.1.1=py27_0
- backports_abc=0.4=py27_0
- beautifulsoup4=4.4.1=py27_0
- bitarray=0.8.1=py27_0
- blaze-core=0.8.3=py27_0
- bokeh=0.10.0=py27_0
- boto=2.38.0=py27_0
- bottleneck=1.0.0=np110py27_0
- cdecimal=2.3=py27_0
- cffi=1.2.1=py27_0
- clyent=1.2.0=py27_0
- colorama=0.3.3=py27_0
- configobj=5.0.6=py27_0
- cryptography=1.0.2=py27_0
- curl=7.45.0=0
- cycler=0.9.0=py27_0
- cython=0.23.4=py27_1
- cytoolz=0.7.4=py27_0
- datashape=0.4.7=np110py27_1
- decorator=4.0.4=py27_0
- docutils=0.12=py27_0
- dynd-python=0.7.0=py27_0
- enum34=1.0.4=py27_0
- fastcache=1.0.2=py27_0
- flask=0.10.1=py27_1
- freetype=2.5.5=0
- funcsigs=0.4=py27_0
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.9=py27_0
- grin=1.2.1=py27_1
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- idna=2.0=py27_0
- ipaddress=1.0.14=py27_0
- ipykernel=4.1.1=py27_0
- ipython=4.0.1=py27_0
- ipython-notebook=4.0.4=py27_0
- ipython-qtconsole=4.0.1=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.0=py27_0
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jdcal=1.0=py27_0
- jedi=0.9.0=py27_0
- jinja2=2.8=py27_0
- jpeg=8d=1
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- launcher=1.0.0=3
- libdynd=0.7.0=0
- libgcc=4.8.5=1
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.8.0=py27_0
- lxml=3.4.4=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.1=py27_0
- mpld3=0.2=py27_0
- multipledispatch=0.4.8=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- ncurses=5.9=1
- networkx=1.10=py27_0
- nlopt=2.4.2=1
- nltk=3.1=py27_0
- node-webkit=0.10.1=0
- nose=1.3.7=py27_0
- notebook=4.0.6=py27_0
- numba=0.22.1=np110py27_0
- numexpr=2.4.4=np110py27_0
- numpy=1.10.2=py27_0
- odo=0.3.4=py27_0
- openpyxl=2.2.6=py27_0
- openssl=1.0.2e=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- patsy=0.4.0=np110py27_0
- pcre=8.31=0
- pep8=1.6.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.0.0=py27_1
- pip=7.1.2=py27_0
- ply=3.8=py27_0
- psutil=3.3.0=py27_0
- ptyprocess=0.5=py27_0
- py=1.4.30=py27_0
- pyasn1=0.1.9=py27_0
- pyaudio=0.2.7=py27_0
- pycosat=0.6.1=py27_0
- pycparser=2.14=py27_0
- pycrypto=2.6.1=py27_0
- pycurl=7.19.5.1=py27_3
- pyflakes=1.0.0=py27_0
- pygments=2.0.2=py27_0
- pyopenssl=0.15.1=py27_1
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- pytest=2.8.1=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=14.7.0=py27_1
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- r=3.2.2=0
- r-assertthat=0.1=r3.2.2_2
- r-base=3.2.2=0
- r-base64enc=0.1_3=r3.2.2_0
- r-bh=1.58.0_1=r3.2.2_0
- r-bitops=1.0_6=r3.2.2_2
- r-boot=1.3_17=r3.2.2_0
- r-car=2.1_0=r3.2.2_0
- r-caret=6.0_62=r3.2.2_0
- r-catools=1.17.1=r3.2.2_2
- r-chron=2.3_47=r3.2.2_0
- r-class=7.3_14=r3.2.2_0
- r-cluster=2.0.3=r3.2.2_0
- r-codetools=0.2_14=r3.2.2_0
- r-colorspace=1.2_6=r3.2.2_0
- r-data.table=1.9.6=r3.2.2_0
- r-dbi=0.3.1=r3.2.2_3
- r-dichromat=2.0_0=r3.2.2_3
- r-digest=0.6.8=r3.2.2_3
- r-dplyr=0.4.3=r3.2.2_0
- r-essentials=1.1=r3.2.2_0
- r-evaluate=0.8=r3.2.2_0
- r-foreach=1.4.3=r3.2.2_0
- r-foreign=0.8_66=r3.2.2_0
- r-formatr=1.2.1=r3.2.2_0
- r-ggplot2=1.0.1=r3.2.2_0
- r-glmnet=2.0_2=r3.2.2_0
- r-gtable=0.1.2=r3.2.2_3
- r-hexbin=1.27.1=r3.2.2_0
- r-highr=0.5.1=r3.2.2_0
- r-htmltools=0.2.6=r3.2.2_2
- r-htmlwidgets=0.5=r3.2.2_0
- r-httpuv=1.3.3=r3.2.2_0
- r-irdisplay=0.3=r3.2.2_0
- r-irkernel=0.5=r3.2.2_1
- r-iterators=1.0.8=r3.2.2_0
- r-jsonlite=0.9.17=r3.2.2_0
- r-kernsmooth=2.23_15=r3.2.2_0
- r-knitr=1.11=r3.2.2_0
- r-labeling=0.3=r3.2.2_2
- r-lattice=0.20_33=r3.2.2_0
- r-lazyeval=0.1.10=r3.2.2_3
- r-lme4=1.1_10=r3.2.2_0
- r-magrittr=1.5=r3.2.2_2
- r-maps=3.0.0_2=r3.2.2_0
- r-markdown=0.7.7=r3.2.2_1
- r-mass=7.3_45=r3.2.2_0
- r-matrix=1.2_2=r3.2.2_0
- r-matrixmodels=0.4_1=r3.2.2_0
- r-mgcv=1.8_9=r3.2.2_0
- r-mime=0.4=r3.2.2_0
- r-minqa=1.2.4=r3.2.2_1
- r-munsell=0.4.2=r3.2.2_2
- r-nlme=3.1_122=r3.2.2_0
- r-nloptr=1.0.4=r3.2.2_2
- r-nnet=7.3_11=r3.2.2_0
- r-pbkrtest=0.4_2=r3.2.2_2
- r-plyr=1.8.3=r3.2.2_0
- r-proto=0.3_10=r3.2.2_2
- r-quantmod=0.4_5=r3.2.2_0
- r-quantreg=5.19=r3.2.2_0
- r-r6=2.1.1=r3.2.2_0
- r-randomforest=4.6_12=r3.2.2_0
- r-rbokeh=0.2.2=r3.2.2_0
- r-rcolorbrewer=1.1_2=r3.2.2_3
- r-rcpp=0.12.2=r3.2.2_0
- r-rcppeigen=0.3.2.5.1=r3.2.2_0
- r-recommended=3.2.2=r3.2.2_0
- r-repr=0.3=r3.2.2_0
- r-reshape2=1.4.1=r3.2.2_2
- r-rjsonio=1.3_0=r3.2.2_1
- r-rmarkdown=0.8.1=r3.2.2_0
- r-rpart=4.1_10=r3.2.2_0
- r-rzmq=0.7.7=r3.2.2_2
- r-scales=0.3.0=r3.2.2_0
- r-shiny=0.12.2=r3.2.2_0
- r-sparsem=1.7=r3.2.2_0
- r-spatial=7.3_11=r3.2.2_0
- r-stringi=1.0_1=r3.2.2_0
- r-stringr=1.0.0=r3.2.2_0
- r-survival=2.38_3=r3.2.2_0
- r-tidyr=0.3.1=r3.2.2_0
- r-ttr=0.23_0=r3.2.2_0
- r-uuid=0.1_2=r3.2.2_0
- r-xtable=1.8_0=r3.2.2_0
- r-xts=0.9_7=r3.2.2_0
- r-yaml=2.1.13=r3.2.2_1
- r-zoo=1.7_12=r3.2.2_1
- readline=6.2=2
- redis=2.6.9=0
- redis-py=2.10.3=py27_0
- requests=2.8.1=py27_0
- rope=0.9.4=py27_1
- rpy2=2.7.0=py27r3.2.2_0
- scikit-image=0.11.3=np110py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.16.1=np110py27_0
- seaborn=0.6.0=np110py27_0
- setuptools=19.2=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.0=py27_0
- sockjs-tornado=1.0.1=py27_0
- sphinx=1.3.1=py27_0
- sphinx_rtd_theme=0.1.7=py27_0
- spyder=2.3.8=py27_0
- spyder-app=2.3.8=py27_0
- sqlalchemy=1.0.9=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np110py27_0
- sympy=0.7.6.1=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- toolz=0.7.4=py27_0
- tornado=4.3=py27_0
- traitlets=4.0.0=py27_0
- ujson=1.33=py27_0
- unicodecsv=0.14.1=py27_0
- werkzeug=0.11.2=py27_0
- wheel=0.26.0=py27_1
- xlrd=0.9.4=py27_0
- xlsxwriter=0.7.7=py27_0
- xlwings=0.5.0=py27_0
- xlwt=1.0.0=py27_0
- xz=5.0.5=0
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - blaze==0.8.3
  - dynd==9b63882
  - ipython-genutils==0.1.0
  - ipython-sql==0.3.6
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - pivottablejs==0.1.0
  - prettytable==0.7.2
  - qgrid==0.2.0
  - sphinx-rtd-theme==0.1.7
  - sqlparse==0.1.18
  - tables==3.2.2
